#!/usr/bin/env python3

import argparse
import os

from osgeo import ogr

ogr.UseExceptions()
driver = ogr.GetDriverByName("ESRI Shapefile")


def _to_file_path(shp_path: str) -> str:
    if shp_path.endswith(".shp"):
        fpath = shp_path
    else:
        os.makedirs(shp_path, exist_ok=True)
        fpath = os.path.join(shp_path, f"{shp_path}.shp")
    if os.path.isfile(fpath):
        driver.DeleteDataSource(fpath)
    return fpath


def extract_polygons(
    out_shp: str, input_shp: str, xmin: float, xmax: float, ymin: float, ymax: float
) -> None:
    src = driver.Open(input_shp, 0)
    dst = driver.CreateDataSource(_to_file_path(out_shp))
    lyr_in = src.GetLayer()
    lyr_in_def = lyr_in.GetLayerDefn()
    srs = lyr_in.GetSpatialRef()
    lyr_out = dst.CreateLayer(lyr_in_def.GetName(), srs=srs, geom_type=ogr.wkbPolygon)
    n_field = lyr_in_def.GetFieldCount()
    for i in range(n_field):
        lyr_out.CreateField(lyr_in_def.GetFieldDefn(i))
    for feat in lyr_in:
        geom = feat.GetGeometryRef()
        if geom.GetGeometryType() == ogr.wkbMultiPolygon:
            polys = list(geom.GetGeometryRef(i) for i in range(geom.GetGeometryCount()))
        elif geom.GetGeometryType() == ogr.wkbPolygon:
            polys = [geom]
        else:
            raise ValueError(f"Unexpected geometry type: {geom.GetGeometryName()}")
        for poly in polys:
            minx, maxx, miny, maxy = poly.GetEnvelope()
            if minx > xmax or maxx < xmin or maxy < ymin or miny > ymax:
                continue
            new_feat = ogr.Feature(lyr_out.GetLayerDefn())
            for i in range(n_field):
                new_feat.SetField(i, feat.GetField(i))
            new_feat.SetGeometry(poly)
            lyr_out.CreateFeature(new_feat)
            new_feat = None
    dst = src = lyr_in = lyr_out = None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("-x", nargs=2, type=float, required=True)
    parser.add_argument("-y", nargs=2, type=float, required=True)
    parser.add_argument("-o", "--output", type=str, required=True)
    parser.add_argument("input", type=str)
    args = parser.parse_args()
    xmin, xmax = args.x
    ymin, ymax = args.y
    extract_polygons(args.output, args.input, xmin, xmax, ymin, ymax)


if __name__ == "__main__":
    main()
