#!/usr/bin/env bash


main() {
    if (("$#" == 0)); then 
        echo "No files provided to count lines" >&2
        return 1
    fi
    local total=0
    local n
    for file in "$@"; do 
        n=$(cat "$file" | sed '/^\s*$/d' | wc -l)
        ((total += n))
    done
    echo "Total of $total non-blank lines of code in $# files"
}

main "$@"
