#!/usr/bin/env bash

declare -A ftps

FTP_URL=
FTP_PASSWORD=

CACHE_FILE=$HOME/.known_ftps

read -r -d '' HELP_MSG <<EOF
CLI to manage FTPs

\e[4m\e[1mUsage\e[0m: ftp <COMMAND> <ARGS>

\e[4m\e[1mCommands\e[0m:
  add       <NAME> <URL> <PWD> Add FTP with specific information
  connect   <NAME> Connect to FTP associated with <NAME>
  download  [-r] <USER:PATH> Download file/directory
  list      Print list of known FTPs
  remove    <NAME> Remove FTP with name <NAME> from know FTPs
  upload    Upload files to directories
  help      Display this message
EOF

load-ftp-data() {
    [[ -f "$CACHE_FILE" ]] || return
    local ftp_usr ftp_url ftp_pwd
    while read -r ftp_usr ftp_url ftp_pwd; do
        ftps["$ftp_usr"]="$ftp_url|$ftp_pwd"
    done <"$CACHE_FILE"
}

save-ftp-data() {
    local content=""
    local ftp_usr ftp_url ftp_pwd
    for ftp_usr in "${!ftps[@]}"; do
        IFS='|' read -r ftp_url ftp_pwd <<<"${ftps["$ftp_usr"]}"
        [[ -z "$ftp_url" ]] && continue
        content="$content$ftp_usr $ftp_url $ftp_pwd\n"
    done
    echo -n -e "$content" > "$CACHE_FILE"
}

get-ftp-data() {
    local ftp_usr="$1"
    if [[ -z "$ftp_usr" ]]; then
        echo -e "\e[31mError: Missing argument <NAME>\e[0m\n" >&2
        echo -e "$HELP_MSG" >&2
        return 1
    fi
    local ftp_data="${ftps[$ftp_usr]}"
    if [[ -z "$ftp_data" ]]; then
        echo -e "\e[31mError: No FTP associated with username '$ftp_usr'\e[0m" >&2
        return 1
    fi
    IFS='|' read -r FTP_URL FTP_PASSWORD <<<"$ftp_data"
}

remove-ftp-data() {
    local ftp_usr="$1"
    if [[ -z "$ftp_usr" ]]; then
        echo -e "\e[31mError: Missing argument <NAME>\e[0m\n" >&2
        echo -e "$HELP_MSG" >&2
        return 1
    fi
    ftps["$ftp_usr"]=
    save-ftp-data
}

print-ftp-list() {
    local ftp_usr
    if (("${#ftps[@]}" == 0)); then
        echo "No FTP recorded"
        return
    fi
    for ftp_usr in "${!ftps[@]}"; do
        echo "$ftp_usr"
    done
}

ftp-connect() {
    local ftp_usr="$1"
    get-ftp-data "$ftp_usr" || return 1
    lftp "$FTP_URL" -u "$ftp_usr","$FTP_PASSWORD"
}

add-ftp-data() {
    local ftp_usr="$1"
    local ftp_url="$2"
    local ftp_pwd="$3"
    if [[ -z "$ftp_usr" || -z "$ftp_url" || -z "$ftp_pwd" ]]; then
        echo -e "\e[31mError: Missing argument <NAME> <URL> <PWD>\e[0m\n" >&2
        echo -e "$HELP_MSG" >&2
        return 1
    fi
    ftps["$ftp_usr"]="$ftp_url|$ftp_pwd"
    save-ftp-data
}

ftp-download() {
    local ftp_usr path my_cmd
    local ftp_path is_file
    if [[ $# == 1 ]]; then
        # Assume it is a file
        is_file=true
        ftp_path="$1"
    elif [[ $# == 2 && $1 == "-r" ]]; then
        # Should be a directory
        is_file=false
        ftp_path="$2"
    else
        echo -e "\e[31mUsage: $0 [-r] <USER:PATH>\e[0m\n" >&2
        echo -e "$HELP_MSG" >&2
        exit 1
    fi

    IFS=":" read -r ftp_usr path <<<"$ftp_path"
    get-ftp-data "$ftp_usr" || return 1

    if $is_file; then
        my_cmd="get $path; exit"
    else
        my_cmd="mirror $path; exit"
    fi

    lftp -u "$ftp_usr,$FTP_PASSWORD" -e "$my_cmd" "$FTP_URL"
}

ftp-upload() {
    local dir_list=()
    local file_list=()
    local i=0
    local ftp_usr
    local destination=
    local my_command=
    for arg in "$@"; do
        if ((i == $# - 1)); then
            destination="$arg"
        elif [[ -d $arg ]]; then
            dir_list+=("$arg")
        elif [[ -f $arg ]]; then
            file_list+=("$arg")
        else
            echo -e "\e[31mInvalid argument: $arg\e[0m\n" >&2
            return 1
        fi
        ((i++))
    done

    IFS=":" read -r ftp_usr dst_path <<<"$destination"
    get-ftp-data "$ftp_usr" || return 1

    if ((${#dir_list[@]} == 0)); then
        my_command="cd $dst_path; mput ${file_list[*]}; exit"
    else
        my_command="mirror -R"
        for dir in "${dir_list[@]}"; do
            my_command+=" -F $dir"
        done
        for file in "${file_list[@]}"; do
            my_command+=" -f $file"
        done
        my_command+=" -O $dst_path; exit"
    fi

    lftp -u "$ftp_usr,$FTP_PASSWORD" -e "$my_command" "$FTP_URL"
}

main() {
    load-ftp-data
    local cmd="$1"
    case "$cmd" in
    "add")
        add-ftp-data "${@:2}"
        ;;
    "remove")
        remove-ftp-data "$2"
        ;;
    "upload")
        ftp-upload "${@:2}"
        ;;
    "download")
        ftp-download "${@:2}"
        ;;
    "connect")
        ftp-connect "$2"
        ;;
    "list")
        print-ftp-list
        ;;
    "help")
        echo -e "$HELP_MSG"
        ;;
    *)
        echo -e "\e[31mUnknown command '$1'\e[0m\n"
        echo -e "$HELP_MSG" >&2
        return  1
        ;;
    esac
}

main "$@"
