#!/bin/bash

function get_ftp_list {
    while fid= read -r line; do
        set -- $line
        echo $1
    done < $HOME/.ftp_passwords
}

function get_ftp_password {
    user=$1
    password=""
    while fid= read -r line; do
        set -- $line
        if [ "$1" = "$user" ]; then
            password=$2
            break
        fi
    done < $HOME/.ftp_passwords
    echo "$password"
}

function ftp_connect {
    user=$1
    password=$(get_ftp_password $user)
    if [ -z "$password" ]; then
        echo "No password found for user $user"
        return 1
    else
        lftp @geo10.elie.ucl.ac.be -u $user,"$password"
    fi
}

function ftp_upload {
    src_path=$1
    user_path=( $(echo $2 | tr ':' ' ') )
    user=${user_path[0]}
    dst_path=${user_path[1]}
    password=$(get_ftp_password $user)

    if [ -z "$password" ]; then
        echo "Password for user $user not found"
        return 1
    fi

    if [ -d "$src_path" ]; then
        my_command="mirror -R $src_path $dst_path; exit"
    else
        my_command="cd $dst_path; mput $src_path; exit"
    fi

    lftp -u $user,$password -e "$my_command" geo10.elie.ucl.ac.be
}


case $1 in
    list) get_ftp_list;;
    password) get_ftp_password $2;;
    connect) ftp_connect $2;;
    upload) ftp_upload $2 $3;;
    *) echo "Unknown command";;
esac
