#!/bin/bash

dir_list=()
file_list=()
i=0
destination=
for arg in "$@"; do
    if (( i == $# - 1 )); then
        destination="$arg"
    elif [[ -d $arg ]]; then
        dir_list+=("$arg")
    elif [[ -f $arg ]]; then
        file_list+=("$arg")
    else
        echo "Invalid argument: $arg"
        exit 1
    fi
    ((i++))
done

user_path=( $(echo $destination | tr ':' ' ') )
user=${user_path[0]}
dst_path=${user_path[1]}
password=$(get_ftp_password $user)

if [ -z "$password" ]; then
    echo "Password for user $user not found"
    exit 1
fi

if (( ${#dir_list[@]} == 0 )); then
    my_command="cd $dst_path; mput ${file_list[@]}; exit"
else
    my_command="mirror -R"
    for dir in "${dir_list[@]}"; do
        my_command+=" -F $dir"
    done
    for file in "${file_list[@]}"; do
        my_command+=" -f $file"
    done
    my_command+=" -O $dst_path; exit"
fi

lftp -u $user,$password -e "$my_command" geo10.elie.ucl.ac.be
