#!/usr/bin/env bash

HELP_MSG="Usage: make-anim -f <format> -d <duration> -o <output-name> [--as-gif] [--small] [--lossy]"

main() {
    lossy=80
    div=2
    gif=false
    duration=-1
    while [[ "$#" -gt 0 ]]; do
        case $1 in
        -f | --frame-format)
            frame_format="$2"
            shift
            ;;
        -d | --duration)
            duration="$2"
            shift
            ;;
        -o | --output-name)
            output_name="$2"
            shift
            ;;
        -s | --small) div=2.66 ;;
        -l | --lossy)
            lossy="$2"
            shift
            ;;
        --as-gif) gif=true ;;
        -h | --help)
            echo "$HELP_MSG"
            exit 0
            ;;
        *)
            echo "Unknown parameter passed: $1" >&2
            echo "$HELP_MSG" >&2
            exit 1
            ;;
        esac
        shift
    done

    counter=0
    while [[ -f $(printf "$frame_format" "$counter") ]]; do
        ((counter++))
    done

    if ((duration <= 0)); then
        echo "Invalid duration: $duration" >&2
        exit 0
    fi

    ((frame_rate = counter / duration))
    if ((frame_rate == 0)); then
        echo "Warning: Duration is too long -> set frame rate to 0.5"
        frame_rate=0.5
    fi

    if ((counter == 0)); then
        echo "No frames matching '$frame_format'" >&2
        return 1
    fi
    ffmpeg -y -r "$frame_rate" -f image2 -vb 5000k -i "$frame_format" \
        -vf "scale=trunc(iw/$div)*2:trunc(ih/$div)*2" -crf 20 -c:v libx264 \
        -tune animation -pix_fmt yuv420p "$output_name.mp4"
    $gif || return
    ffmpeg -y -i "$output_name.mp4" -filter_complex "[0:v] palettegen" palette.png
    ffmpeg -y -i "$output_name.mp4" -i palette.png -filter_complex "[0:v][1:v] paletteuse" "$output_name.gif"
    if ! [ -x "$(command -v gifsicle)" ]; then
        echo "gifsicle is not installed. Skipping optimization"
        return
    fi
    optimized=$(printf "%s_optimized.gif" "$output_name")
    gifsicle -O3 --lossy="$lossy" --colors 256 "$output_name".gif -o "$optimized"
}

main "$@"
