#!/usr/bin/env bash

n=60
if [[ -n "$1" ]]; then
    n="$1"
fi

width=$(tput cols)
if ((n > width + 20)); then
    echo "The screen width ($width) is too narrow for colormaps with $n colors."
    exit 1
fi

read -r -d '' pythonscript <<EOF
from matplotlib import colormaps
n=$n
x = list(i / (n - 1) for i in range(n))
for name, cm in colormaps.items():
    if name.endswith("_r"):
        continue
    rgb_values = []
    for c in cm(x):
        rgb = list(map(lambda v: str(round(v*255)), c[:3]))
        rgb_values.append(','.join(rgb))
    print("{} {}".format(name, ';'.join(rgb_values)))
EOF

while read -r name cmap; do
    IFS=';' read -ra rgbvalues <<<"$cmap"
    for rgb in "${rgbvalues[@]}"; do
        IFS=',' read -r red green blue <<<"$rgb"
        printf "\x1b[38;2;%d;%d;%dm█\x1b[0m" "$red" "$green" "$blue"
    done
    echo " $name"
done < <(python3 -c "$pythonscript") | less -r
