#!/usr/bin/env bash

shopt -s extglob

remove-white-space() {
    local file="$1"
    local newfile
    # whitespaces replaced by one single underscore
    newfile=${file//+( )/_}
    # deal with dashes
    newfile=${newfile//_-/-}
    newfile=${newfile//-_/-}
    [[ "$file" == "$newfile" ]] || mv "$file" "$newfile"
}

main() {
    local entry
    if (("$#" > 0)); then
        for entry in "$@"; do
            remove-white-space "$entry"
        done
        return 0
    fi
    for entry in *" "*; do
        [[ "$entry" == "* *" ]] && continue
        remove-white-space "$entry"
    done
}

main "$@"
