#!/usr/bin/env bash

_pem_completion() {
    ((COMP_CWORD <= 2)) || return 0
    local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
    local latest="${COMP_WORDS[$COMP_CWORD]}"
    local commands="add amend get help list remove"
    local saved_names
    local words=""
    if [[ -f $HOME/.local/pem/envs ]]; then
        readarray -t saved_names < <(cat $HOME/.local/pem/envs | cut -d " " -f 1)
    fi
    case "$prev" in
        add | list | help)
            ;;
        remove | get | amend)
            words="${saved_names[*]}"
            ;;
        *)
            words="$commands"
            ;;
    esac
    COMPREPLY=($(compgen -W "$words" -- "$latest"))
    return 0
}

complete -F _pem_completion -o default -o bashdefault pem

_pem_names() {
    local options
    local latest="${COMP_WORDS[$COMP_CWORD]}"
    if [[ -f $HOME/.local/pem/envs ]]; then
        readarray -t options < <(cat $HOME/.local/pem/envs | cut -d " " -f 1)
    fi
    COMPREPLY=($(compgen -W "${options[*]}" -- "$latest"))
}

activate-env() {
    if (("$#" == 0)); then
        echo "Missing environment name" >&2
        return 1
    fi
    local activate_path
    activate_path=$(~/.local/scripts/pem get "$1") || return 1
    source "$activate_path"
}

complete -F _pem_names activate-env

_spm_completion() {
    ((COMP_CWORD <= 2)) || return 0
    local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
    local latest="${COMP_WORDS[$COMP_CWORD]}"
    local commands="add get help list remove"
    local saved_names
    local words=""
    if [[ -f "$HOME/.sharepoints" ]]; then
        readarray -t saved_names < <(cat $HOME/.sharepoints | cut -d " " -f 1)
    fi
    case "$prev" in
        add | list | help)
            ;;
        remove | get)
            words="${saved_names[*]}"
            ;;
        *)
            words="$commands"
            ;;
    esac
    COMPREPLY=($(compgen -W "$words" -- "$latest"))
}

complete -F _spm_completion -o default -o bashdefault spm

_spm_names() {
    local options
    local latest="${COMP_WORDS[$COMP_CWORD]}"
    readarray -t options < <(cat $HOME/.sharepoints | cut -d " " -f 1)
    COMPREPLY=($(compgen -W "${options[*]}" -- "$latest"))
}

jmp() {
    local name="$1"
    local path="$(~/.local/scripts/spm get "$1")" || return 1
    cd "$path"
}

complete -F _spm_names jmp

_ftp_completion() {
    ((COMP_CWORD <= 2)) || return 0
    local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
    local latest="${COMP_WORDS[$COMP_CWORD]}"
    local commands="add connect download help list remove upload"
    local ftp_usrs
    local words=""
    if [[ -f "$HOME/.known_ftps" ]]; then
        readarray -t ftp_usrs < <(cat $HOME/.known_ftps | cut -d " " -f 1)
    fi
    case "$prev" in
        add | list | help | upload | download)
            ;;
        remove | connect)
            words="${ftp_usrs[*]}"
            ;;
        *)
            words="$commands"
            ;;
    esac
    COMPREPLY=($(compgen -W "$words" -- "$latest"))
}

complete -F _ftp_completion -o default -o bashdefault ftp-dobby
